server:
    bind:
        host: 0.0.0.0
        port: 80
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    language: en-US
    cors: true
    pretty_print: true
    limit: 10
    # templates: /path/to/templates
    map:
        url: https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png
        attribution: '<a href="https://wikimediafoundation.org/wiki/Maps_Terms_of_Use">Wikimedia maps</a> | Map data &copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'

logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: Boskalis cpt-manager
        description: Provides an API to geospatial data
        keywords:
            - geospatial
            - data
            - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: http://boskalis.com
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Boskalis
        url: https://boskalis.com
    contact:
        name: Betman, Maarten
        position: Geotechnical Engineer
        address: ntb
        city: Papendrecht
        stateorprovince: Zuid Holland
        postalcode: ntb
        country: Netherlands
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: maarten.betman@boskalis.com
        url: https://www.boskalis.com/
        hours: 07:00 till 19:00
        instructions: During hours of service.  Off on weekends.
        role: pointOfContact

resources:
  point:
    type: collection
    title: CPT Locations
    description: cpt locations
    keywords:
      - cpt
      - point
    links:
      - type: text/html
        rel: canonical
        title: information
        href: http://www.naturalearthdata.com/
        hreflang: en-US
    extents:
      spatial:
        bbox: [ 0, 0, 52724, 48346 ]
        crs: https://www.opengis.net/def/crs/EPSG/0/3414
      temporal:
        begin:
        end: null  # or empty
    providers:
      - type: feature
        name: pygeoapi_mssql_provider.mssql.MsSqlProvider
        data:
          server: 10.64.32.62
          database: test_engdep
          user: api
          password: api
        id_field: ID
        table: POINT
        geom_field: GEOM
        source_srid: 3414